# Generated by Django 5.1.2 on 2024-10-23 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('title', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('rating', models.IntegerField(blank=True, default=2, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
    ]
